# Generated by Django 5.2.7 on 2025-12-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_product_max_stock_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='dashboard.customer'),
        ),
    ]
